ci_executor_max_load: 10

ansible_host: '{{address}}'
ansible_user: root

address: 10.157.2.55
network: 10.157.2.0
netmask: 255.255.255.0
gateway: 10.157.2.1
dns-nameservers: 10.158.0.53
dns-search: zhdk.ch
