ansible_host: ci.zhdk.ch

ansible_user: root

ci_server_virtual_hosts:
- hostname: '{{ci_server_external_hostname}}'
  ip: '*'
  force_redirect_to_https: yes
  ssl_certificate_file: /etc/letsencrypt/live/ci.zhdk.ch/fullchain.pem
  ssl_certificate_key_file: /etc/letsencrypt/live/ci.zhdk.ch/privkey.pem

job_retention_duration: 10 Years
task_retention_duration: 10 Years
trial_retention_duration: 100 Days

address: 195.176.247.161
#network 195.176.247.129
#broadcast 195.176.247.129
netmask: 255.255.255.192
gateway: 195.176.247.129
dns-nameservers: 10.158.0.53
dns-search: zhdk.ch


